import { getVendors, saveVendor, savePOR, clearAllData } from './storage'

const mockVendors = [
  {
    id: 'v-001',
    name: 'Acme Consulting LLC',
    dba: 'Acme',
    contactEmail: 'contracts@acmeconsulting.com',
    contactName: 'Sarah Johnson',
    contactPhoneNumber: '555-123-4567',
    isAuthorizedSigner: true,
    status: 'active',
    axonEntity: 'TAS',
    requiresNDA: true,
    requiresPrivacy: false,
    requiresInfoSec: false,
    createdAt: '2025-01-15T10:00:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: true,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-002',
    name: 'Robert Half International',
    dba: 'Robert Half',
    contactEmail: 'vendor.relations@roberthalf.com',
    contactName: 'Michael Chen',
    contactPhoneNumber: '555-234-5678',
    isAuthorizedSigner: true,
    status: 'active',
    axonEntity: 'TAS',
    requiresNDA: false,
    requiresPrivacy: true,
    requiresInfoSec: false,
    createdAt: '2025-02-01T14:30:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: true,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-003',
    name: 'CloudSecure Technologies',
    dba: null,
    contactEmail: 'sales@cloudsecure.io',
    contactName: 'Emily Rodriguez',
    contactPhoneNumber: '555-345-6789',
    isAuthorizedSigner: true,
    status: 'pending',
    axonEntity: 'SEG',
    requiresNDA: true,
    requiresPrivacy: true,
    requiresInfoSec: true,
    createdAt: '2025-11-20T09:15:00Z',
    documents: {
      msaSigned: false,
      w9Uploaded: true,
      bankingComplete: false,
      quoteUploaded: false,
    },
  },
  {
    id: 'v-004',
    name: 'DataFlow Analytics Inc',
    dba: 'DataFlow',
    contactEmail: 'partnerships@dataflow.com',
    contactName: 'James Wilson',
    contactPhoneNumber: '555-456-7890',
    isAuthorizedSigner: false,
    status: 'incomplete',
    axonEntity: 'CAN',
    requiresNDA: true,
    requiresPrivacy: false,
    requiresInfoSec: true,
    createdAt: '2025-12-01T11:00:00Z',
    documents: {
      msaSigned: false,
      w9Uploaded: false,
      bankingComplete: false,
      quoteUploaded: false,
    },
  },
  {
    id: 'v-005',
    name: 'Sterling Office Supplies',
    dba: 'Sterling',
    contactEmail: 'accounts@sterlingoffice.com',
    contactName: 'Linda Park',
    contactPhoneNumber: '555-567-8901',
    isAuthorizedSigner: true,
    status: 'active',
    axonEntity: 'TAS',
    requiresNDA: false,
    requiresPrivacy: false,
    requiresInfoSec: false,
    createdAt: '2025-03-10T16:45:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: true,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-006',
    name: 'Apex Training Solutions',
    dba: 'Apex',
    contactEmail: 'info@apextraining.co',
    contactName: 'Robert Martinez',
    contactPhoneNumber: '555-678-9012',
    isAuthorizedSigner: true,
    status: 'pending',
    axonEntity: 'AUK',
    requiresNDA: false,
    requiresPrivacy: true,
    requiresInfoSec: false,
    createdAt: '2025-12-05T08:30:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: false,
      bankingComplete: true,
      quoteUploaded: false,
    },
  },
]

// Helper to create a date X days ago
function daysAgo(days) {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

// Requestors
const REQUESTORS = {
  jane: { name: 'Jane Smith', email: 'jane.smith@axon.com' },
  tom: { name: 'Tom Bradley', email: 'tom.bradley@axon.com' },
  sarah: { name: 'Sarah Chen', email: 'sarah.chen@axon.com' },
  mike: { name: 'Mike Johnson', email: 'mike.johnson@axon.com' },
}

// Assignee rules based on POR amount:
// - Brittany Bagley: Over $1M
// - Dave Iacovelli: $250K - $1M
// - Jennifer Mak: Under $250K
function getAssigneeByAmount(amount) {
  if (amount >= 1000000) {
    return 'Brittany Bagley'
  } else if (amount >= 250000) {
    return 'Dave Iacovelli'
  } else {
    return 'Jennifer Mak'
  }
}

const mockPORs = [
  // === Jane Smith's PORs (her own, already processed) ===
  {
    id: 'POR-001',
    vendorId: 'v-001',
    vendorName: 'Acme Consulting LLC',
    name: 'Q1 Strategy Consulting Engagement',
    description: 'Q1 Strategy Consulting Engagement',
    costCenter: 'CC-1001 Engineering',
    profitCenter: 'PC-1001 Engineering',
    projectCode: 'PROJ-2025-001',
    country: 'USA - United States',
    attachments: 'SOW_Acme_Q1.pdf',
    lineItems: [
      {
        id: 'li-001',
        line: 1,
        productName: 'Strategy consulting services',
        lineAmount: '15000',
        category: '6400 - Consulting',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Acme Consulting LLC',
        vendorKey: 'v-001',
        startDate: '2025-01-15',
        endDate: '2025-03-31',
        billingFrequency: 'Monthly',
      },
    ],
    netAmount: 15000,
    totalAmount: 15000,
    currency: 'USD',
    status: 'approved',
    submittedAt: daysAgo(12),
    createdAt: daysAgo(12),
    createdBy: REQUESTORS.jane.email,
    requestor: REQUESTORS.jane.name,
    requestorEmail: REQUESTORS.jane.email,
    assignee: 'Jennifer Mak', // $15K < $250K
  },
  {
    id: 'POR-002',
    vendorId: 'v-002',
    vendorName: 'Robert Half International',
    name: 'Annual Engineering Staff Augmentation Contract',
    description: 'Annual Engineering Staff Augmentation Contract',
    costCenter: 'CC-1001 Engineering',
    profitCenter: 'PC-1001 Engineering',
    projectCode: 'PROJ-2025-002',
    country: 'USA - United States',
    attachments: 'MSA_RobertHalf_2025.pdf, SOW_Engineering.pdf',
    lineItems: [
      {
        id: 'li-002',
        line: 1,
        productName: 'Senior Software Engineers (8 FTE x 12 months)',
        lineAmount: '1920000',
        category: '6100 - Professional Services',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Robert Half International',
        vendorKey: 'v-002',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        billingFrequency: 'Monthly',
      },
      {
        id: 'li-003',
        line: 2,
        productName: 'QA Engineers (4 FTE x 12 months)',
        lineAmount: '720000',
        category: '6100 - Professional Services',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Robert Half International',
        vendorKey: 'v-002',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        billingFrequency: 'Monthly',
      },
    ],
    netAmount: 2640000,
    totalAmount: 2640000,
    currency: 'USD',
    status: 'sent_to_dynamics',
    submittedAt: daysAgo(15),
    createdAt: daysAgo(15),
    createdBy: REQUESTORS.jane.email,
    requestor: REQUESTORS.jane.name,
    requestorEmail: REQUESTORS.jane.email,
    assignee: 'Brittany Bagley', // $2.64M > $1M
  },
  {
    id: 'POR-003',
    vendorId: 'v-005',
    vendorName: 'Sterling Office Supplies',
    name: 'Office Equipment Refresh',
    description: 'Office Equipment Refresh',
    costCenter: 'CC-1004 Operations',
    profitCenter: 'PC-1004 Operations',
    projectCode: '',
    country: 'USA - United States',
    attachments: 'Quote_Sterling_Chairs.pdf',
    lineItems: [
      {
        id: 'li-004',
        line: 1,
        productName: 'Ergonomic Office Chairs (25 units)',
        lineAmount: '2500',
        category: '6300 - Hardware',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Sterling Office Supplies',
        vendorKey: 'v-005',
        startDate: '2025-02-01',
        endDate: '2025-02-15',
        billingFrequency: 'Upon Delivery',
      },
    ],
    netAmount: 2500,
    totalAmount: 2500,
    currency: 'USD',
    status: 'approved',
    submittedAt: daysAgo(7),
    createdAt: daysAgo(7),
    createdBy: REQUESTORS.jane.email,
    requestor: REQUESTORS.jane.name,
    requestorEmail: REQUESTORS.jane.email,
    assignee: 'Jennifer Mak',
  },

  // === Tom Bradley's PORs (pending approval) ===
  {
    id: 'POR-004',
    vendorId: 'v-001',
    vendorName: 'Acme Consulting LLC',
    name: 'Enterprise Digital Transformation Initiative',
    description: 'Enterprise Digital Transformation Initiative',
    costCenter: 'CC-1001 Engineering',
    profitCenter: 'PC-1001 Engineering',
    projectCode: 'PROJ-2025-DT',
    country: 'USA - United States',
    attachments: 'SOW_DigitalTransformation.pdf, ROI_Analysis.pdf',
    lineItems: [
      {
        id: 'li-005',
        line: 1,
        productName: 'Strategy & Assessment Phase',
        lineAmount: '450000',
        category: '6400 - Consulting',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Acme Consulting LLC',
        vendorKey: 'v-001',
        startDate: '2025-02-01',
        endDate: '2025-04-30',
        billingFrequency: 'Monthly',
      },
      {
        id: 'li-006',
        line: 2,
        productName: 'Implementation Phase',
        lineAmount: '875000',
        category: '6400 - Consulting',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Acme Consulting LLC',
        vendorKey: 'v-001',
        startDate: '2025-05-01',
        endDate: '2025-10-31',
        billingFrequency: 'Monthly',
      },
      {
        id: 'li-007',
        line: 3,
        productName: 'Change Management & Training',
        lineAmount: '175000',
        category: '6500 - Training',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Acme Consulting LLC',
        vendorKey: 'v-001',
        startDate: '2025-09-01',
        endDate: '2025-12-31',
        billingFrequency: 'Milestone (Only if noted in legal contract)',
      },
    ],
    netAmount: 1500000,
    totalAmount: 1500000,
    currency: 'USD',
    status: 'submitted',
    submittedAt: daysAgo(2),
    createdAt: daysAgo(2),
    createdBy: REQUESTORS.tom.email,
    requestor: REQUESTORS.tom.name,
    requestorEmail: REQUESTORS.tom.email,
    assignee: 'Brittany Bagley', // $1.5M > $1M
  },
  {
    id: 'POR-005',
    vendorId: 'v-003',
    vendorName: 'CloudSecure Technologies',
    name: 'Cloud Infrastructure Security Upgrade',
    description: 'Cloud Infrastructure Security Upgrade',
    costCenter: 'CC-1001 Engineering',
    profitCenter: 'PC-1001 Engineering',
    projectCode: 'PROJ-2025-SEC',
    country: 'USA - United States',
    attachments: 'Proposal_CloudSecure.pdf, SecurityAssessment.pdf',
    lineItems: [
      {
        id: 'li-008',
        line: 1,
        productName: 'Security assessment and remediation',
        lineAmount: '185000',
        category: '6100 - Professional Services',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'CloudSecure Technologies',
        vendorKey: 'v-003',
        startDate: '2025-02-01',
        endDate: '2025-05-31',
        billingFrequency: 'Monthly',
      },
      {
        id: 'li-009',
        line: 2,
        productName: 'Annual security monitoring license',
        lineAmount: '155000',
        category: '6200 - Software Subscriptions',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'CloudSecure Technologies',
        vendorKey: 'v-003',
        startDate: '2025-06-01',
        endDate: '2026-05-31',
        billingFrequency: 'Annual',
      },
    ],
    netAmount: 340000,
    totalAmount: 340000,
    currency: 'USD',
    status: 'submitted',
    submittedAt: daysAgo(4),
    createdAt: daysAgo(4),
    createdBy: REQUESTORS.tom.email,
    requestor: REQUESTORS.tom.name,
    requestorEmail: REQUESTORS.tom.email,
    assignee: 'Dave Iacovelli', // $340K is $250K-$1M
  },

  // === Sarah Chen's PORs ===
  {
    id: 'POR-006',
    vendorId: 'v-001',
    vendorName: 'Acme Consulting LLC',
    name: 'Market Research Analysis',
    description: 'Market Research Analysis',
    costCenter: 'CC-1003 Marketing',
    profitCenter: 'PC-1003 Marketing',
    projectCode: 'PROJ-2024-MKT',
    country: 'USA - United States',
    attachments: 'Proposal_MarketResearch.pdf',
    lineItems: [
      {
        id: 'li-010',
        line: 1,
        productName: 'Competitive market analysis report',
        lineAmount: '8750',
        category: '6400 - Consulting',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Acme Consulting LLC',
        vendorKey: 'v-001',
        startDate: '2024-11-01',
        endDate: '2024-12-15',
        billingFrequency: 'Upon Completion',
      },
    ],
    netAmount: 8750,
    totalAmount: 8750,
    currency: 'USD',
    status: 'rejected',
    submittedAt: daysAgo(14),
    createdAt: daysAgo(14),
    createdBy: REQUESTORS.sarah.email,
    requestor: REQUESTORS.sarah.name,
    requestorEmail: REQUESTORS.sarah.email,
    assignee: 'Jennifer Mak', // $8.75K < $250K
    rejectionReason: 'Budget not approved for Q4. Please resubmit for Q1 budget cycle.',
  },
  {
    id: 'POR-007',
    vendorId: 'v-003',
    vendorName: 'CloudSecure Technologies',
    name: 'Annual Software Licenses Renewal',
    description: 'Annual Software Licenses Renewal',
    costCenter: 'CC-1001 Engineering',
    profitCenter: 'PC-1001 Engineering',
    projectCode: '',
    country: 'USA - United States',
    attachments: 'Quote_Licenses_2025.pdf',
    lineItems: [
      {
        id: 'li-011',
        line: 1,
        productName: 'Enterprise security suite (500 seats)',
        lineAmount: '125000',
        category: '6200 - Software Subscriptions',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'CloudSecure Technologies',
        vendorKey: 'v-003',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        billingFrequency: 'Annual',
      },
    ],
    netAmount: 125000,
    totalAmount: 125000,
    currency: 'USD',
    status: 'submitted',
    submittedAt: daysAgo(6),
    createdAt: daysAgo(6),
    createdBy: REQUESTORS.sarah.email,
    requestor: REQUESTORS.sarah.name,
    requestorEmail: REQUESTORS.sarah.email,
    assignee: 'Jennifer Mak', // $125K < $250K
  },

  // === Mike Johnson's PORs ===
  {
    id: 'POR-008',
    vendorId: 'v-002',
    vendorName: 'Robert Half International',
    name: 'Executive Assistant Placement',
    description: 'Executive Assistant Placement',
    costCenter: 'CC-1004 Operations',
    profitCenter: 'PC-1004 Operations',
    projectCode: '',
    country: 'USA - United States',
    attachments: 'Placement_Agreement.pdf',
    lineItems: [
      {
        id: 'li-012',
        line: 1,
        productName: 'Executive Assistant placement fee',
        lineAmount: '22000',
        category: '6100 - Professional Services',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Robert Half International',
        vendorKey: 'v-002',
        startDate: '2025-01-15',
        endDate: '2025-01-15',
        billingFrequency: 'Upfront',
      },
    ],
    netAmount: 22000,
    totalAmount: 22000,
    currency: 'USD',
    status: 'submitted',
    submittedAt: daysAgo(9),
    createdAt: daysAgo(9),
    createdBy: REQUESTORS.mike.email,
    requestor: REQUESTORS.mike.name,
    requestorEmail: REQUESTORS.mike.email,
    assignee: 'Jennifer Mak', // $22K < $250K
  },
  {
    id: 'POR-009',
    vendorId: 'v-006',
    vendorName: 'Apex Training Solutions',
    name: 'Annual Trade Show Booth & Materials',
    description: 'Annual Trade Show Booth & Materials',
    costCenter: 'CC-1003 Marketing',
    profitCenter: 'PC-1003 Marketing',
    projectCode: 'PROJ-2025-TRADE',
    country: 'USA - United States',
    attachments: 'TradeShow_Quote.pdf, BoothDesign.pdf',
    lineItems: [
      {
        id: 'li-013',
        line: 1,
        productName: 'Trade show booth rental (3 events)',
        lineAmount: '45000',
        category: '6100 - Professional Services',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Apex Training Solutions',
        vendorKey: 'v-006',
        startDate: '2025-03-01',
        endDate: '2025-09-30',
        billingFrequency: 'Quarterly',
      },
      {
        id: 'li-014',
        line: 2,
        productName: 'Marketing materials and swag',
        lineAmount: '33000',
        category: '6100 - Professional Services',
        currency: 'USD',
        purposeCode: '',
        vendorName: 'Apex Training Solutions',
        vendorKey: 'v-006',
        startDate: '2025-02-01',
        endDate: '2025-02-28',
        billingFrequency: 'Upfront',
      },
    ],
    netAmount: 78000,
    totalAmount: 78000,
    currency: 'USD',
    status: 'submitted',
    submittedAt: daysAgo(3),
    createdAt: daysAgo(3),
    createdBy: REQUESTORS.mike.email,
    requestor: REQUESTORS.mike.name,
    requestorEmail: REQUESTORS.mike.email,
    assignee: 'Jennifer Mak', // $78K < $250K
  },
]

export function seedVendors() {
  // Only seed if no vendors exist
  if (getVendors().length === 0) {
    mockVendors.forEach(vendor => saveVendor(vendor))
    console.log('Seeded mock vendors')
  }
}

// Create all demo data (vendors + PORs)
export function createDemoData() {
  clearAllData()
  mockVendors.forEach(vendor => saveVendor(vendor))
  mockPORs.forEach(por => savePOR(por))
  console.log('Created demo data: 6 vendors, 9 PORs (4 requestors)')
}
