import { getVendors, saveVendor } from './storage'

const mockVendors = [
  {
    id: 'v-001',
    name: 'Acme Consulting LLC',
    dba: 'Acme',
    contactEmail: 'contracts@acmeconsulting.com',
    contactName: 'Sarah Johnson',
    contactPhoneNumber: '555-123-4567',
    isAuthorizedSigner: true,
    status: 'active',
    axonEntity: 'TAS',
    requiresNDA: true,
    requiresPrivacy: false,
    requiresInfoSec: false,
    createdAt: '2025-01-15T10:00:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: true,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-002',
    name: 'Robert Half International',
    dba: 'Robert Half',
    contactEmail: 'vendor.relations@roberthalf.com',
    contactName: 'Michael Chen',
    contactPhoneNumber: '555-234-5678',
    isAuthorizedSigner: true,
    status: 'active',
    axonEntity: 'TAS',
    requiresNDA: false,
    requiresPrivacy: true,
    requiresInfoSec: false,
    createdAt: '2025-02-01T14:30:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: true,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-003',
    name: 'CloudSecure Technologies',
    dba: null,
    contactEmail: 'sales@cloudsecure.io',
    contactName: 'Emily Rodriguez',
    contactPhoneNumber: '555-345-6789',
    isAuthorizedSigner: true,
    status: 'pending',
    axonEntity: 'SEG',
    requiresNDA: true,
    requiresPrivacy: true,
    requiresInfoSec: true,
    createdAt: '2025-11-20T09:15:00Z',
    documents: {
      msaSigned: false,
      w9Uploaded: true,
      bankingComplete: false,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-004',
    name: 'DataFlow Analytics Inc',
    dba: 'DataFlow',
    contactEmail: 'partnerships@dataflow.com',
    contactName: 'James Wilson',
    contactPhoneNumber: '555-456-7890',
    isAuthorizedSigner: false,
    status: 'incomplete',
    axonEntity: 'CAN',
    requiresNDA: true,
    requiresPrivacy: false,
    requiresInfoSec: true,
    createdAt: '2025-12-01T11:00:00Z',
    documents: {
      msaSigned: false,
      w9Uploaded: false,
      bankingComplete: false,
      quoteUploaded: false,
    },
  },
  {
    id: 'v-005',
    name: 'Sterling Office Supplies',
    dba: 'Sterling',
    contactEmail: 'accounts@sterlingoffice.com',
    contactName: 'Linda Park',
    contactPhoneNumber: '555-567-8901',
    isAuthorizedSigner: true,
    status: 'active',
    axonEntity: 'TAS',
    requiresNDA: false,
    requiresPrivacy: false,
    requiresInfoSec: false,
    createdAt: '2025-03-10T16:45:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: true,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
  {
    id: 'v-006',
    name: 'Apex Training Solutions',
    dba: 'Apex',
    contactEmail: 'info@apextraining.co',
    contactName: 'Robert Martinez',
    contactPhoneNumber: '555-678-9012',
    isAuthorizedSigner: true,
    status: 'pending',
    axonEntity: 'AUK',
    requiresNDA: false,
    requiresPrivacy: true,
    requiresInfoSec: false,
    createdAt: '2025-12-05T08:30:00Z',
    documents: {
      msaSigned: true,
      w9Uploaded: false,
      bankingComplete: true,
      quoteUploaded: true,
    },
  },
]

export function seedVendors() {
  // Only seed if no vendors exist
  if (getVendors().length === 0) {
    mockVendors.forEach(vendor => saveVendor(vendor))
    console.log('Seeded mock vendors')
  }
}

